### PR TITLE
Combined rules as suggest by Marc Z.

### PR DESCRIPTION
**Pull request by jsight**
This uses a hack to combine the rules. It seems to work. :)

### CODE REVIEW

**Comment by jsight** [comment]
I think the "found" thing is present in a lot of other places as well. Can you try to catch those into this PR as well?

**Comment by mareknovotny** [comment]
I looked only for "found" in titles, there are found in messages, but those should be fine to keep, or not?

**Comment by mareknovotny** [comment]
This find 
`find rules-reviewed/ -type f -name '*.windup.xml' -exec grep found {} \; -print`

gives me:
```
                     An embedded resource adapter descriptor ('ra.xml') has been found. Resource adapters implement the Java Connector Architecture (JCA) for a particular Enterprise Information System (EIS).  
rules-reviewed/openshift/jca.windup.xml
                        The XML schema documentation can be found within the WebSphere Application Server 7.0 directory under `/web/configDocs/packages/appdeployment/Deployment.html`.
rules-reviewed/eap6/websphere/websphere-xml.windup.xml
                                Tibco `com.tibco.{package-remainder}.{type}` reference found.
                        <message>SAP CrystalReports `com.crystaldecisions.{package-remainder}.{type}` reference found.
                        <message>IONA `com.iona.{package-remainder}.{type}` reference found.
                          <message>Apache `org.apache.{subpackage}` API reference found.
                        <message>`org.{subpackage}.{package-remainder}{type}` reference found. No specific details available.</message>
                        <message>`java.sql.DriverManager` type reference found. No specific details available.</message>
rules-reviewed/eap6/uncategorized/generic-catchall.windup.xml
                      <message>EAP 7 includes a new API for building Singleton services, which significantly simplifies the process, and solves the issues found in the legacy solution.</message>
rules-reviewed/eap7/eap6/eap6.windup.xml
                        The XML schema documentation can be found within the WebSphere Application Server 7.0 directory under `/web/configDocs/packages/appdeployment/Deployment.html`.
rules-reviewed/eap7/websphere/websphere-xml.windup.xml
                      <message>EAP 7 includes a new API for building Singleton services, which significantly simplifies the process, and solves the issues found in the legacy solution.</message>
rules-reviewed/eap7/eap5/jboss-eap5-7-java.windup.xml
                                This listener requires a composite service binding in Fuse Service Works. The configuration for a JCA or JMS binding can be found in the jms-bus definition
                            can be found in the ftp-bus definition associated with this listener.
                            The configuration for a Camel binding can be found in the camel-bus definition associated
                            A good example of this functionality can be found in the quickstarts project in the [rules-camel-jbr
rules-reviewed/fuse-service-works/soa-p-5/soa-p-5.windup.xml

**Comment by jsight** [comment]
Yes, you are right... it looks like there are no other ones in the titles. I think that is fine.

**Pull request merged**
